from enum import Enum


class CustomerAttributeReservedName(str, Enum):
    TELEMETRY_DECK_APP_ID = "telemetry_deck_app_id"
    TELEMETRY_DECK_USER_ID = "telemetry_deck_user_id"
    VALUE_0 = "$ad"
    VALUE_1 = "$adGroup"
    VALUE_10 = "$appsflyerSharingFilter"
    VALUE_11 = "$attConsentStatus"
    VALUE_12 = "$branchId"
    VALUE_13 = "$brazeAliasLabel"
    VALUE_14 = "$brazeAliasName"
    VALUE_15 = "$campaign"
    VALUE_16 = "$clevertapId"
    VALUE_17 = "$creative"
    VALUE_18 = "$displayName"
    VALUE_19 = "$email"
    VALUE_2 = "$adjustId"
    VALUE_20 = "$fbAnonId"
    VALUE_21 = "$fcmTokens"
    VALUE_22 = "$firebaseAppInstanceId"
    VALUE_23 = "$gpsAdId"
    VALUE_24 = "$idfa"
    VALUE_25 = "$idfv"
    VALUE_26 = "$ip"
    VALUE_27 = "$iterableCampaignId"
    VALUE_28 = "$iterableTemplateId"
    VALUE_29 = "$iterableUserId"
    VALUE_3 = "$airshipChannelId"
    VALUE_30 = "$keyword"
    VALUE_31 = "$kochavaDeviceId"
    VALUE_32 = "$mediaSource"
    VALUE_33 = "$mixpanelDistinctId"
    VALUE_34 = "$mparticleId"
    VALUE_35 = "$onesignalId"
    VALUE_36 = "$onesignalUserId"
    VALUE_37 = "$phoneNumber"
    VALUE_38 = "$posthogUserId"
    VALUE_39 = "$telemetryDeckUserId"
    VALUE_4 = "$amazonAdId"
    VALUE_40 = "$telemetryDeckAppId"
    VALUE_43 = "$segmentId"
    VALUE_44 = "$tenjinId"
    VALUE_45 = "$deviceVersion"
    VALUE_5 = "$amplitudeDeviceId"
    VALUE_6 = "$amplitudeUserId"
    VALUE_7 = "$appleRefundHandlingPreference"
    VALUE_8 = "$apnsTokens"
    VALUE_9 = "$appsflyerId"

    def __str__(self) -> str:
        return str(self.value)
